# Generated by Django 4.1.7 on 2023-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="ci",
            field=models.CharField(
                max_length=11,
                null=True,
                unique=True,
                verbose_name="identification number",
            ),
        ),
    ]
