# Generated by Django 4.1.7 on 2023-04-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0002_alter_systemuser_ci"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(unique=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "area",
                "verbose_name_plural": "areas",
            },
        ),
        migrations.CreateModel(
            name="EmployeeResponsability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(unique=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "responsability",
                "verbose_name_plural": "responsabilities",
            },
        ),
        migrations.AddField(
            model_name="systemuser",
            name="area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users_app.employeearea",
                verbose_name="area or department",
            ),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="responsability",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users_app.employeeresponsability",
                verbose_name="responsability or main tasks",
            ),
        ),
    ]
