# Generated by Django 4.1.7 on 2023-04-05 14:20

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        (
            "users_app",
            "0003_employeearea_employeeresponsability_systemuser_area_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created timestamp",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemuser",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.historicalvault",
                verbose_name="historical vault",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemuser",
            name="updated_timestamp",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Updated timestamp"),
        ),
    ]
