# Generated by Django 4.1.7 on 2023-04-12 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0006_alter_systemuser_ci_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users_app.employeearea",
                verbose_name="area or department",
            ),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="responsability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users_app.employeeresponsability",
                verbose_name="responsability or main tasks",
            ),
        ),
    ]
