# Generated by Django 4.1.7 on 2023-04-12 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0007_alter_systemuser_area_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemuser",
            options={
                "verbose_name": "System user",
                "verbose_name_plural": "Syestem users",
            },
        ),
    ]
