# Generated by Django 4.1.7 on 2023-04-19 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0008_alter_systemuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemuser",
            options={
                "verbose_name": "System user",
                "verbose_name_plural": "System users",
            },
        ),
    ]
