# Generated by Django 4.1.7 on 2023-05-04 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0009_alter_systemuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="phone_1",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only numeric characters allowed", regex="^\\+[0-9]+$"
                    )
                ],
                verbose_name="phone number 1",
            ),
        ),
    ]
