# Generated by Django 4.1.7 on 2023-05-04 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0011_alter_systemuser_phone_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="phone_2",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only numeric characters allowed", regex="^\\+?\\d+$"
                    )
                ],
                verbose_name="phone number 2",
            ),
        ),
    ]
