# Generated by Django 4.1.7 on 2023-05-04 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users_app", "0012_systemuser_phone_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created timestamp"
                    ),
                ),
                (
                    "updated_timestamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated timestamp"
                    ),
                ),
                ("topic", models.CharField(max_length=30, verbose_name="topic")),
                ("text", models.TextField(blank=True, null=True, verbose_name="text")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attachments/",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="date"),
                ),
                (
                    "historical_vault",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.historicalvault",
                        verbose_name="historical vault",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "System email",
                "verbose_name_plural": "System emails",
            },
        ),
    ]
