# Generated by Django 4.1.7 on 2023-05-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("users_app", "0013_systememail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systememail",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.historicalvault",
                verbose_name="NOT USED",
            ),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.historicalvault",
                verbose_name="NOT USED",
            ),
        ),
    ]
