# Generated by Django 4.1.7 on 2023-04-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(unique=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "classification",
                "verbose_name_plural": "classifications",
            },
        ),
    ]
