# Generated by Django 4.1.7 on 2023-04-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0002_creating_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
