# Generated by Django 4.1.7 on 2023-04-18 06:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0003_alter_classification_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualPackaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="capacity",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(max_length=20, verbose_name="measurement unit"),
                ),
            ],
            options={
                "verbose_name": "Individual packaging",
                "verbose_name_plural": "Individual packagings",
            },
        ),
        migrations.CreateModel(
            name="GroupingPackaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("capacity", models.PositiveSmallIntegerField(verbose_name="capacity")),
                (
                    "individual_packaging",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grouping_packaging",
                        to="products_app.individualpackaging",
                        verbose_name="Individual packaging",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grouping packaging",
                "verbose_name_plural": "Grouping packagings",
            },
        ),
    ]
