# Generated by Django 4.1.7 on 2023-04-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0004_individualpackaging_groupingpackaging"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="name"),
                ),
                (
                    "symbol",
                    models.CharField(max_length=10, unique=True, verbose_name="symbol"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("mililiters", models.PositiveIntegerField(verbose_name="mililiters")),
            ],
            options={
                "verbose_name": "measurement unit",
                "verbose_name_plural": "measurement units",
            },
        ),
        migrations.AlterField(
            model_name="individualpackaging",
            name="measurement_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="products_app.measurementunit",
                verbose_name="measurement unit",
            ),
        ),
    ]
