# Generated by Django 4.1.7 on 2023-04-21 05:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("products_app", "0006_creating_initial_measurement_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupingpackaging",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 4, 21, 5, 19, 34, 965592, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Created timestamp",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupingpackaging",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.historicalvault",
                verbose_name="historical vault",
            ),
        ),
        migrations.AddField(
            model_name="groupingpackaging",
            name="updated_timestamp",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated timestamp"
            ),
        ),
        migrations.AddField(
            model_name="individualpackaging",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created timestamp",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="individualpackaging",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.historicalvault",
                verbose_name="historical vault",
            ),
        ),
        migrations.AddField(
            model_name="individualpackaging",
            name="updated_timestamp",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated timestamp"
            ),
        ),
    ]
