# Generated by Django 4.1.7 on 2023-04-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0007_groupingpackaging_created_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="destination"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
            ],
            options={
                "verbose_name": "destination",
                "verbose_name_plural": "destinations",
            },
        ),
    ]
