# Generated by Django 4.1.7 on 2023-04-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0008_destination"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="entity"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="phone"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
            ],
            options={
                "verbose_name": "entity",
                "verbose_name_plural": "entities",
            },
        ),
    ]
