# Generated by Django 4.1.7 on 2023-04-22 05:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("products_app", "0010_alter_destination_name_alter_entity_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created timestamp"
                    ),
                ),
                (
                    "updated_timestamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated timestamp"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="name"),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="wholesale price",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="amount")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="amount",
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products_app.classification",
                    ),
                ),
                (
                    "distribution_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products_app.groupingpackaging",
                        verbose_name="distribution format",
                    ),
                ),
                (
                    "historical_vault",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.historicalvault",
                        verbose_name="historical vault",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "productss",
            },
        ),
    ]
