# Generated by Django 4.1.7 on 2023-04-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0012_alter_product_options_alter_product_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_production",
            field=models.BooleanField(default=True, verbose_name="in production"),
        ),
    ]
