# Generated by Django 4.1.7 on 2023-04-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0014_product_unique_product_format_and_major_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=30, verbose_name="name"),
        ),
    ]
