# Generated by Django 4.1.7 on 2023-04-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0015_alter_product_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="The cost has to be smaller than the wholesale_price",
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("cost__lt", models.F("wholesale_price"))),
                name="The cost has to be smaller than the wholesale_price",
            ),
        ),
    ]
