# Generated by Django 4.1.7 on 2023-04-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products_app",
            "0016_remove_product_the cost has to be smaller than the wholesale_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="The cost has to be smaller than the wholesale_price",
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("cost__lt", models.F("wholesale_price"))),
                name="cost_smaller_than_wholesale_price",
            ),
        ),
    ]
