# Generated by Django 4.1.7 on 2023-05-04 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "products_app",
            "0017_remove_product_the cost has to be smaller than the wholesale_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="phone",
        ),
    ]
