# Generated by Django 4.1.7 on 2023-05-04 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0018_remove_entity_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="phone_1",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only numeric characters allowed", regex="^\\+?\\d+$"
                    )
                ],
                verbose_name="phone number 1",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="phone_2",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only numeric characters allowed", regex="^\\+?\\d+$"
                    )
                ],
                verbose_name="phone number 2",
            ),
        ),
    ]
