# Generated by Django 4.1.7 on 2023-05-05 22:00

import django.db.models.deletion
from django.db import migrations, models, transaction


@transaction.atomic
def create_formats(apps, schema_editor):
    Format = apps.get_model("products_app", "Format")
    Format.objects.bulk_create(
        [
            Format(name="Paquete"),
            Format(name="Pomo"),
            Format(name="A granel"),
            Format(name="Caja"),
        ]
    )


def remove_format(apps, schema_editor):
    Format = apps.get_model("products_app", "Format")
    Format.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "products_app",
            "0021_remove_product_cost_smaller_than_wholesale_price_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Format",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "format",
                "verbose_name_plural": "formats",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="products_app.format",
            ),
        ),
        migrations.RunPython(create_formats, migrations.RunPython.noop),
    ]
