# Generated by Django 4.1.7 on 2023-05-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("products_app", "0023_individualpackaging_is_grouping_packaging"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupingpackaging",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.historicalvault",
                verbose_name="NOT USED",
            ),
        ),
        migrations.AlterField(
            model_name="individualpackaging",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.historicalvault",
                verbose_name="NOT USED",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.historicalvault",
                verbose_name="NOT USED",
            ),
        ),
    ]
