# Generated by Django 4.1.7 on 2023-05-30 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_historicalvault_author"),
        ("products_app", "0025_production_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupingpackaging",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.historicalvault",
                verbose_name="NOT USED",
            ),
        ),
        migrations.AlterField(
            model_name="individualpackaging",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.historicalvault",
                verbose_name="NOT USED",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.historicalvault",
                verbose_name="NOT USED",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="historical_vault",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.historicalvault",
                verbose_name="NOT USED",
            ),
        ),
    ]
