# Generated by Django 4.2.1 on 2023-06-25 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0027_product_description_production_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products_app.destination",
                verbose_name="Destination",
            ),
        ),
    ]
