# Generated by Django 4.2.1 on 2023-06-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0029_production_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
    ]
