# Generated by Django 4.2.1 on 2023-07-01 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0030_alter_classification_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupingpackaging",
            name="capacity",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="capacity",
            ),
        ),
    ]
