# Generated by Django 4.2.1 on 2023-08-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0031_alter_groupingpackaging_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="distribution_format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productions",
                to="products_app.groupingpackaging",
                verbose_name="distribution format",
            ),
        ),
    ]
