# Generated by Django 4.2.1 on 2023-08-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0032_alter_production_distribution_format"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entity",
            options={
                "ordering": ["name"],
                "verbose_name": "UEB",
                "verbose_name_plural": "UEBs",
            },
        ),
        migrations.AlterField(
            model_name="production",
            name="entity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products_app.entity",
                verbose_name="UEB",
            ),
        ),
    ]
