# Generated by Django 4.2.1 on 2023-08-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0033_alter_entity_options_alter_production_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="production_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="production date"
            ),
        ),
    ]
