# Generated by Django 4.2.1 on 2023-09-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0034_production_production_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualpackaging",
            name="material",
            field=models.CharField(
                choices=[("P", "plástico"), ("V", "vidirio")],
                default="V",
                max_length=1,
                verbose_name="Material",
            ),
        ),
    ]
