# Generated by Django 4.2.1 on 2023-09-16 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0035_individualpackaging_material"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupingpackaging",
            options={"verbose_name": "Embalaje", "verbose_name_plural": "Embalajes"},
        ),
        migrations.AlterModelOptions(
            name="individualpackaging",
            options={
                "verbose_name": "Tipo de embase",
                "verbose_name_plural": "Tipos de embases",
            },
        ),
    ]
