# Generated by Django 4.2.1 on 2023-09-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0037_alter_classification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualpackaging",
            name="material",
            field=models.CharField(
                choices=[("P", "Plástico"), ("V", "Vidrio")],
                default="V",
                max_length=1,
                verbose_name="Material",
            ),
        ),
    ]
