# Generated by Django 4.2.1 on 2023-09-26 04:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_historicalvault_author"),
        ("products_app", "0038_alter_individualpackaging_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="production",
            name="entity",
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created timestamp"
                    ),
                ),
                (
                    "updated_timestamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated timestamp"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="Nombre"),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        default=2023,
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=2023)
                        ],
                        verbose_name="Año",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ],
                        default=9,
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=9)
                        ],
                        verbose_name="Mes",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Cantidad"),
                ),
                (
                    "destiny",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="products_app.destination",
                    ),
                ),
                (
                    "historical_vault",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.historicalvault",
                        verbose_name="NOT USED",
                    ),
                ),
                (
                    "measurement_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="products_app.measurementunit",
                        verbose_name="Unidad de medida",
                    ),
                ),
                (
                    "product_kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="products_app.classification",
                        verbose_name="Tipo de producto",
                    ),
                ),
                (
                    "ueb",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="products_app.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan",
                "verbose_name_plural": "planes",
            },
        ),
        migrations.AddField(
            model_name="production",
            name="plan",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production",
                to="products_app.plan",
                verbose_name="plan",
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                fields=("product_kind", "year", "month"),
                name="unique_product_year_month_in_plan",
            ),
        ),
    ]
