# Generated by Django 4.2.1 on 2023-10-05 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0039_remove_production_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementunit",
            name="used_for_planning",
            field=models.BooleanField(default=False, verbose_name="used for planning"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Enero"),
                    (2, "Febrero"),
                    (3, "Marzo"),
                    (4, "Abril"),
                    (5, "Mayo"),
                    (6, "Junio"),
                    (7, "Julio"),
                    (8, "Agosto"),
                    (9, "Septiembre"),
                    (10, "Octubre"),
                    (11, "Noviembre"),
                    (12, "Diciembre"),
                ],
                default=10,
                validators=[django.core.validators.MinValueValidator(limit_value=10)],
                verbose_name="Mes",
            ),
        ),
    ]
