# Generated by Django 4.2.1 on 2024-01-03 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0040_measurementunit_used_for_planning_alter_plan_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="format",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="groupingpackaging",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="individualpackaging",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="measurementunit",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Enero"),
                    (2, "Febrero"),
                    (3, "Marzo"),
                    (4, "Abril"),
                    (5, "Mayo"),
                    (6, "Junio"),
                    (7, "Julio"),
                    (8, "Agosto"),
                    (9, "Septiembre"),
                    (10, "Octubre"),
                    (11, "Noviembre"),
                    (12, "Diciembre"),
                ],
                default=1,
                validators=[django.core.validators.MinValueValidator(limit_value=1)],
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="year",
            field=models.PositiveSmallIntegerField(
                default=2024,
                validators=[django.core.validators.MinValueValidator(limit_value=2024)],
                verbose_name="Año",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="description"
            ),
        ),
    ]
