# Generated by Django 4.2.1 on 2025-01-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0041_alter_classification_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Enero"),
                    (2, "Febrero"),
                    (3, "Marzo"),
                    (4, "Abril"),
                    (5, "Mayo"),
                    (6, "Junio"),
                    (7, "Julio"),
                    (8, "Agosto"),
                    (9, "Septiembre"),
                    (10, "Octubre"),
                    (11, "Noviembre"),
                    (12, "Diciembre"),
                ],
                verbose_name="Mes",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="Año"),
        ),
    ]
