# Generated by Django 4.2.1 on 2025-02-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0042_alter_plan_month_alter_plan_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupingpackaging",
            name="name",
            field=models.CharField(max_length=30, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="individualpackaging",
            name="name",
            field=models.CharField(max_length=30, verbose_name="name"),
        ),
    ]
