# Generated by Django 4.2.1 on 2025-02-20 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0043_alter_groupingpackaging_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualpackaging",
            name="capacity",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="capacity",
            ),
        ),
    ]
