# Generated by Django 4.2.1 on 2025-09-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0044_alter_individualpackaging_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Nombre"),
        ),
    ]
