# Generated by Django 4.2.1 on 2025-09-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0045_alter_plan_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Nombre"),
        ),
    ]
