# Generated by Django 4.2.1 on 2025-10-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0046_alter_plan_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="plan",
            name="unique_product_year_month_in_plan",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="month",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="quantity",
        ),
        migrations.AddField(
            model_name="plan",
            name="apr_quantity",
            field=models.FloatField(default=0, verbose_name="Plan abril"),
        ),
        migrations.AddField(
            model_name="plan",
            name="aug_quantity",
            field=models.FloatField(default=0, verbose_name="Plan agosto"),
        ),
        migrations.AddField(
            model_name="plan",
            name="dec_quantity",
            field=models.FloatField(default=0, verbose_name="Plan diciembre"),
        ),
        migrations.AddField(
            model_name="plan",
            name="feb_quantity",
            field=models.FloatField(default=0, verbose_name="Plan febrero"),
        ),
        migrations.AddField(
            model_name="plan",
            name="jan_quantity",
            field=models.FloatField(default=0, verbose_name="Plan enero"),
        ),
        migrations.AddField(
            model_name="plan",
            name="jul_quantity",
            field=models.FloatField(default=0, verbose_name="Plan julio"),
        ),
        migrations.AddField(
            model_name="plan",
            name="jun_quantity",
            field=models.FloatField(default=0, verbose_name="Plan junio"),
        ),
        migrations.AddField(
            model_name="plan",
            name="mar_quantity",
            field=models.FloatField(default=0, verbose_name="Plan marzo"),
        ),
        migrations.AddField(
            model_name="plan",
            name="may_quantity",
            field=models.FloatField(default=0, verbose_name="Plan mayo"),
        ),
        migrations.AddField(
            model_name="plan",
            name="nov_quantity",
            field=models.FloatField(default=0, verbose_name="Plan noviembre"),
        ),
        migrations.AddField(
            model_name="plan",
            name="oct_quantity",
            field=models.FloatField(default=0, verbose_name="Plan octubre"),
        ),
        migrations.AddField(
            model_name="plan",
            name="sep_quantity",
            field=models.FloatField(default=0, verbose_name="Plan septiembre"),
        ),
    ]
