# Generated by Django 4.2.1 on 2025-10-09 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0047_remove_plan_unique_product_year_month_in_plan_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "verbose_name": "Producción",
                "verbose_name_plural": "Producciones",
            },
        ),
        migrations.RemoveField(
            model_name="production",
            name="description",
        ),
        migrations.AddField(
            model_name="production",
            name="extra_info",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="Información Extra"
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="production",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Costo",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="distribution_format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productions",
                to="products_app.groupingpackaging",
                verbose_name="Formato de distribución",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="production",
            name="plan",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productions",
                to="products_app.plan",
                verbose_name="plan",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productions",
                to="products_app.product",
                verbose_name="Producciones",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="production_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de producción"
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="production",
            name="wholesale_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Precio al por mayor",
            ),
        ),
    ]
