# Generated by Django 4.2.1 on 2025-12-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0048_alter_production_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="extra_plan",
            field=models.BooleanField(default=False, verbose_name="Plan extra"),
        ),
    ]
